version: '1'
services:
  api:
    image: amazoncorretto:11.0.19
    container_name: leiturando-api
    working_dir: /usr/src/api
    volumes:
      - ./target/Leiturando-0.0.1-SNAPSHOT.jar:/usr/src/api/Leiturando.jar
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://leiturando-db:5432/leiturando
      - DB_USERNAME=gustavo
      - DB_PASSWORD=admin
    command: [ "java", "-jar", "Leiturando.jar" ]

  db:
    image: postgres:16-alpine
    container_name: leiturando-db
    environment:
      POSTGRES_DB: leiturando
      POSTGRES_USER: gustavo
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: