# Configurações do datasource
spring.datasource.url=jdbc:postgresql://ep-misty-thunder-06745571.us-east-2.aws.neon.tech/neondb
spring.datasource.username=Gust4voSiqueira
spring.datasource.password=gZwYrhCyv78W
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações de inicialização do SQL
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

# Configurações de segurança
security.oauth2.resource.id=bcrypt

# Porta do servidor
server.port=8080
